package com.github.f4b6a3.uniqueness;

import java.util.HashSet;
import java.util.UUID;

import com.github.f4b6a3.uuid.UuidCreator;
import com.github.f4b6a3.uuid.exception.UuidCreatorException;
import com.github.f4b6a3.uuid.factory.TimeBasedUuidCreator;
import com.github.f4b6a3.uuid.timestamp.StoppedDefaultTimestampStrategy;
import com.github.f4b6a3.uuid.util.LogUtil;

/**
 * This test starts many threads that keep requesting thousands of time-based
 * UUIDs to a single generator.
 * 
 * The theoretical maximum amount of UUIDs that can be generated at the same
 * millisecond by a single generator without duplicated UUIDs is about 163
 * million UUIDs. It's calculated by the product of the clock sequence range and
 * the count of 100 nanosecond intervals per millisecond, that is:
 * 
 * 16,384 * 10,000 = 163,840,000.
 * 
 * My personal PC don't have enough memory and processor to test the generation
 * of 163 million UUIDs. So the amount of UUIDs generated by this test is not
 * too high.
 *
 * Each UUID is reduced to a `long` value to use less memory. The timestamp high
 * bits and the node identifier bits are ignored since they don't change.
 * 
 * The timestamp strategy used is {@link StoppedDefaultTimestampStrategy} which
 * always returns the same timestamp.
 * 
 * An exception is thrown if a UUID value is generated more than once.
 * 
 */
public class UniquenessTest {

	private int threadCount; // Number of threads to run
	private int requestCount; // Number of requests for thread

	// private long[][] cacheLong; // Store values generated per thread
	private HashSet<Long> hashSet;

	private boolean verbose; // Show progress or not

	// Time based UUID creator
	private TimeBasedUuidCreator creator;

	/**
	 * Initialize the test.
	 * 
	 * @param threadCount
	 * @param requestCount
	 * @param creator
	 */
	public UniquenessTest(int threadCount, int requestCount, TimeBasedUuidCreator creator, boolean progress) {
		this.threadCount = threadCount;
		this.requestCount = requestCount;
		this.creator = creator;
		this.verbose = progress;
		this.initCache();
	}

	private void initCache() {
		this.hashSet = new HashSet<>();
	}

	/**
	 * Initialize and start the threads.
	 */
	public void start() {

		Thread[] threads = new Thread[this.threadCount];

		// Instantiate and start many threads
		for (int i = 0; i < this.threadCount; i++) {
			threads[i] = new Thread(new UniquenessTestThread(i, verbose));
			threads[i].start();
		}

		// Wait all the threads to finish
		for (Thread thread : threads) {
			try {
				thread.join();
			} catch (InterruptedException e) {
				// Do nothing 
			}
		}
	}

	public class UniquenessTestThread implements Runnable {

		private int id;
		private boolean verbose;

		public UniquenessTestThread(int id, boolean verbose) {
			this.id = id;
			this.verbose = verbose;
		}

		/**
		 * Run the test.
		 */
		@Override
		public void run() {

			long msb = 0;
			long lsb = 0;
			long value = 0;
			double progress = 0;
			int max = requestCount;

			for (int i = 0; i < max; i++) {

				// Request a UUID
				UUID uuid = null;
				try {
					uuid = creator.create();
				} catch (UuidCreatorException e) {
					// Ignore the overrun exception and try again
					uuid = creator.create();
				}

				// Convert UUID into a long value, ignoring fixed bits
				msb = uuid.getMostSignificantBits() & 0xffffffffffff0000L;
				lsb = (uuid.getLeastSignificantBits() & 0xffff000000000000L) >>> 48;

				value = (msb | lsb);

				if (verbose) {
					// Calculate and show progress
					progress = (i * 1.0 / max) * 100;
					if (progress % 1 == 0) {
						LogUtil.log(String.format("[Thread %06d] %s %s %s%%", id, uuid, i, (int) progress));
					}
				}

				// Insert the value in cache, if it does not exist in it.
				if (!hashSet.add((Long)value)) {
					throw new UuidCreatorException(
							String.format("[DUPLICATE][Thread %s] %s %s %s%%", id, uuid, i, (int) progress));
				}
			}

			if (verbose) {
				// Finished
				LogUtil.log(String.format("[Thread %s] Done.", id));
			}
		}
	}

	public static void execute(boolean verbose, int threadCount, int requestCount) {
		TimeBasedUuidCreator creator = UuidCreator.getTimeBasedCreator()
				.withTimestampStrategy(new StoppedDefaultTimestampStrategy());

		UniquenessTest test = new UniquenessTest(threadCount, requestCount, creator, verbose);
		test.start();
	}

	public static void main(String[] args) {
		boolean verbose = true;
		int threadCount = 16; // Number of threads to run
		int requestCount = 1_000_000; // Number of requests for thread
		execute(verbose, threadCount, requestCount);
	}
}
